### PR TITLE
Added Enhanced Ecommerce Impression.

### PR DESCRIPTION
**Pull request by basdag**
**Content**

+ Created [Enhanced Ecommerce Impression](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#impression-data) class.
+ Created EnhancedEcommerceHit as parent class for Enhanced Ecommerce hits, which will differ from the already existing Hit parent class in some points.
+ Created EnhancedEcommerceHits for temporarily storing Enhanced Ecommerce hits. The class will allow to attach Enhanced Ecommerce hits to any other hit that is not of type Ecommerce.
+ Refactored Analytics.send(hit) functionality to be able to attach Enhanced Ecommerce hits.
+ Updated README to reflect the new Enhanced Ecommerce Impression functionality.
+ Updated package.json version to reflect the new functionality.

### CODE REVIEW

**Comment by GingerBear** [comment]
~~~I suggest adding usage of `Enhanced Ecommerce`~~~ already added

**Comment by GingerBear** [comment]
looks like regular event support ab testing https://github.com/react-native-community/react-native-google-analytics/blob/master/lib/Hit.js#L10

Not sure if Ecommerce event should also support.

**Comment by GingerBear** [comment]
maybe it's just me, but I am not familiar with the concept of Enhanced Ecommerce Impression. I found it helpful if we can add a brief intro of `Enhanced Ecommerce Impression` and some links in the pr.

**Comment by GingerBear** [comment]
instead of creating `EnhancedEcommerceHit.js`, is that possible to create `EnhancedEcommerce.js` under `hits/`that extends the existing `Hit` like all the other hits. I found the file structure is more concise that way. 

Same goes to `EnhancedEcommerceHits.js` and `impression.js`

**Comment by basdag** [comment]
1) Good question about the experiment - a/b testing - functionality. Since the enhanced e-commerce events are been attach to regular events, we still maintain the support for experiments.

2) Good suggestion I would add a link to Enhanced Ecommerce impression into the PR comments.

3) ~~~Regarding the structure, the reason why I did not follow the existent structure was because the HIT [definition](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#hit) by GA does not include any of the enhanced ecommerce events. Also the parent of the enhanced ecommerce events would not use the required `t` property by the Hit class, they would use different ones that are require among these types of events. What I could do to clarify a little bit is to remove the `Hit` post fix word from the class name `EnhancedEcommerceHits.js` -> `EnhancedEcommerce.js` to avoid confusion with regular hits.~~~ Good suggestion what I ended doing is make `Impression` inherit from `Hit`, remove `EnhancedEcommerceHits`, and leave `EnhancedEcommerce` inherit directly from `Serialize`

**Pull request closed without merging**
